version: "3"

services:
  server:
    image: whatsapp-not-a-contact-bot
    build: .
    restart: always
    volumes:
      - ${PWD}/logs:/app/logs
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file: prod.env
